name: ape
description: Ape application for Gorilla project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # 据说是为了在 ios 上运行而必须添加的
  flutter_cupertino_localizations: ^1.0.1

  # 红色角标 https://github.com/yako-dev/flutter_badges
  badges: ^1.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # 图片下载缓存 https://github.com/Baseflow/flutter_cached_network_image
  cached_network_image: ^2.2.0

  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.3

  # 网络库 https://github.com/flutterchina/dio
  dio: ^3.0.9

  # 支持特殊格式的文本编辑域  https://github.com/fluttercandies/extended_text_field:
  extended_text_field: ^0.5.0

  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: 0.2.6+1

  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.5.4

  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6

  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.6.3

  # 图片选取器
  image_picker: ^0.6.6+4

  # 格式化
  intl: 0.16.0

  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.2.1

  keyboard_visibility: ^0.5.6

  # 点赞按钮 https://github.com/fluttercandies/like_button
  like_button: ^1.0.1

  # 本地json对象存储  https://github.com/lesnitsky/flutter_localstorage
  localstorage: ^3.0.0

  # Toast 插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.3.2

  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^4.0.5+1

  # 上拉加载和下拉刷新组件 https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^1.5.7

  # 谁用谁闪亮  https://github.com/hnvn/flutter_shimmer
  shimmer: ^1.1.1

  # sqlite 插件 https://github.com/tekartik/sqflite
  sqflite: ^1.3.0

  # https://github.com/flutter/plugins
  shared_preferences: ^0.5.7

  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 5.4.2

  # 官方 webview https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^0.3.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/common/
    - assets/images/home/
    - assets/images/login/
    - assets/images/logo/
    - assets/images/splash/
    - assets/images/wode/
